# ╔═══════════════════════════════════════════════════════════════════╗
# ║                         Mouse & Touchpad                         ║
# ╚═══════════════════════════════════════════════════════════════════╝
# Mouse and touchpad configuration

input {
    touchpad {
        natural_scroll = yes
        disable_while_typing = false
        clickfinger_behavior = true
        scroll_factor = 0.5
    }
}
