
# --- window.conf ---
# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# See https://wiki.hyprland.org/Configuring/Window-Rules/

# '$&' is a hyde specific shorthand for "override" \\ analogous to a reference
# This symbol indicates that the following values will override the default configuration
$&=override

windowrule = opacity 0.95 0.80, class:^.*$
